### ISSUE TITLE
sonar-scanner -X    ERROR: SonarQube server [http://10.12.12.12:9000] can not be reached

### ISSUE THREAD

**Issue by klin111** [SonarSource/sonar-scanning-examples#119]
23:27:25.936 INFO: Scanner configuration file: /Users/admin/Downloads/sonar-scanner-4.4.0.2170-macosx/conf/sonar-scanner.properties
23:27:25.940 INFO: Project root configuration file: /Users/admin/jenkins_agent/workspace/kefuduan-clinet-useful-test-job/check-code-ios-lib-mgxskin/sonar-project.properties
23:27:25.971 INFO: SonarScanner 4.4.0.2170
23:27:25.971 INFO: Java 11.0.3 AdoptOpenJDK (64-bit)
23:27:25.971 INFO: Mac OS X 10.15.5 x86_64
23:27:26.114 DEBUG: keyStore is : 
23:27:26.115 DEBUG: keyStore type is : pkcs12
23:27:26.115 DEBUG: keyStore provider is : 
23:27:26.115 DEBUG: init keystore
23:27:26.115 DEBUG: init keymanager of type SunX509
23:27:26.231 DEBUG: Create: /Users/admin/.sonar/cache
23:27:26.233 INFO: User cache: /Users/admin/.sonar/cache
23:27:26.233 DEBUG: Create: /Users/admin/.sonar/cache/_tmp
23:27:26.235 DEBUG: Extract sonar-scanner-api-batch in temp...
23:27:26.239 DEBUG: Get bootstrap index...
23:27:26.240 DEBUG: Download: http://10.12.12.12:9000/batch/index
23:27:26.304 ERROR: SonarQube server [http://10.12.12.12:9000] can not be reached
23:27:26.304 INFO: ------------------------------------------------------------------------
23:27:26.304 INFO: EXECUTION FAILURE
23:27:26.304 INFO: ------------------------------------------------------------------------
23:27:26.305 INFO: Total time: 0.395s
23:27:26.313 INFO: Final Memory: 3M/14M
23:27:26.313 INFO: ------------------------------------------------------------------------
23:27:26.314 ERROR: Error during SonarScanner execution
org.sonarsource.scanner.api.internal.ScannerException: Unable to execute SonarScanner analysis
	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.lambda$createLauncher$0(IsolatedLauncherFactory.java:85)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher(IsolatedLauncherFactory.java:74)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher(IsolatedLauncherFactory.java:70)
	at org.sonarsource.scanner.api.EmbeddedScanner.doStart(EmbeddedScanner.java:185)
	at org.sonarsource.scanner.api.EmbeddedScanner.start(EmbeddedScanner.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:73)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.IllegalStateException: Fail to get bootstrap index from server
	at org.sonarsource.scanner.api.internal.BootstrapIndexDownloader.getIndex(BootstrapIndexDownloader.java:42)
	at org.sonarsource.scanner.api.internal.JarDownloader.getScannerEngineFiles(JarDownloader.java:58)
	at org.sonarsource.scanner.api.internal.JarDownloader.download(JarDownloader.java:53)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.lambda$createLauncher$0(IsolatedLauncherFactory.java:76)
	... 7 more
Caused by: java.lang.IllegalStateException: Status returned by url [http://10.12.12.12:9000/batch/index] is not valid: [404]
	at org.sonarsource.scanner.api.internal.ServerConnection.callUrl(ServerConnection.java:116)
	at org.sonarsource.scanner.api.internal.ServerConnection.downloadString(ServerConnection.java:99)
	at org.sonarsource.scanner.api.internal.BootstrapIndexDownloader.getIndex(BootstrapIndexDownloader.java:39)
	... 10 more

**Comment by sylvain-combe-sonarsource** [comment]
Hello
your scanner connectivity problem is not related to the scanning examples in this repository.
Feel free to reach out to the community at https://community.sonarsource.com/ for support.
