### ISSUE TITLE
failed to push the analyst report to server

### ISSUE THREAD

**Issue by speedooo** [SonarSource/sonar-scanning-examples#4]
I did install and run sonarQube and Mysql on my localhost. I got the erroe message when i run "ant all" under the ant project.

[sonar:sonar] CPD calculation finished
[sonar:sonar] Analysis report generated in 55ms, dir size=13 KB
[sonar:sonar] Analysis reports compressed in 5ms, zip size=5 KB

BUILD FAILED
/home/developer/sonarQube/workspace/sonar-scanning-examples-master/sonarqube-scanner-ant/build.xml:43: org.sonarqube.ws.client.HttpException: Error 500 on http://localhost:9000/api/ce/submit?projectKey=org.sonarqube:sonarqube-scanner-ant&projectName=Example%20of%20SonarQube%20Scanner%20for%20Ant%20Usage : {"errors":[{"msg":"An error has occurred. Please contact your administrator."}]}
	at org.sonarqube.ws.client.BaseResponse.failIfNotSuccessful(BaseResponse.java:36)
	at org.sonar.scanner.bootstrap.BatchWsClient.failIfUnauthorized(BatchWsClient.java:102)
	at org.sonar.scanner.bootstrap.BatchWsClient.call(BatchWsClient.java:71)
	at org.sonar.scanner.report.ReportPublisher.upload(ReportPublisher.java:173)
	at org.sonar.scanner.report.ReportPublisher.execute(ReportPublisher.java:128)
	at org.sonar.scanner.phases.PublishPhaseExecutor.publishReportJob(PublishPhaseExecutor.java:64)
	at org.sonar.scanner.phases.PublishPhaseExecutor.executeOnRoot(PublishPhaseExecutor.java:51)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:81)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.ant.SonarQubeTask.launchAnalysis(SonarQubeTask.java:99)
	at org.sonarsource.scanner.ant.SonarQubeTask.execute(SonarQubeTask.java:81)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:853)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)

Do i need some username or token for push report to server?

Thasnk

kevin

**Comment by dbmeneses** [comment]
Hi, could you please open a topic in https://groups.google.com/forum/#!forum/sonarqube ?
It appears that there was an error on the server side, so if possible please include the any relevant logs in [sonarqube_home]/logs/sonar.log and the version of SonarQube that you are using.

By default no authentication is needed to push to the server, otherwise it depends on the settings.

**Comment by mail2ganeshcse** [comment]
Please help for the below error.. since i am running the sonar-scanner command directly on jenkins machine it works and genrates sonar reports to sonar dashboard, but its not happening in jenkins pipelin.. it throw below error...

0:56:07.723 DEBUG: Upload report
20:56:07.782 DEBUG: POST 400 http://xx.xx.xx.xx:9000/api/ce/submit?projectKey=stage-project-admin-Dsonar.projectName%3DGD-admin-Dsonar.language%3Dts-Dsonar.sources%3D%2Fhome%2Fjenkins%2Fworkspace%2Fstage-branch-admin%2Fdist%2Fproject-admin%2F-Dsonar.tests%3D%2Fhome%2Fjenkins%2Fworkspace%2Fstage-branch-admin%2Fdist%2Fproject-admin%2F | time=58ms
20:56:07.790 DEBUG: eslint-bridge server will shutdown
20:56:07.958 DEBUG: stylelint-bridge server will shutdown
20:56:07.961 INFO: ------------------------------------------------------------------------
20:56:07.961 INFO: EXECUTION FAILURE
20:56:07.961 INFO: ------------------------------------------------------------------------
20:56:07.961 INFO: Total time: 1:22.233s
20:56:08.103 INFO: Final Memory: 33M/1424M

**Comment by jeff-zapotoczny-sonarsource** [comment]
Hello @mail2ganeshcse: you're commenting on an issue that was closed 3 years ago. I suggest instead you post your request for help at our [Community forum](https://community.sonarsource.com/).

**Comment by mail2ganeshcse** [comment]
I couldn't find the solution for the issue's.. could you plz share the solution link or url
